* Auto-generated by build_study_data.py.
VARIABLE LABELS
 ParticipantID 'Participant ID'
 BG_Age18Plus 'Age 18 or older'
 BG_PriorArchitecture 'Previously studied computer architecture or computer organisation'
 BG_PriorVR 'Used a VR headset before'
 BG_VRExperience 'VR experience level'
 BG_PriorConfidence 'Pre-session confidence in computer architecture'
 BG_PriorDifficulty 'Perceived difficulty of core architecture topics'
 BG_Studied_InstructionFlow 'Previously studied topic: Instruction Flow'
 BG_Studied_Pipelining 'Previously studied topic: Pipelining'
 BG_Studied_Stack 'Previously studied topic: Stack'
 BG_Studied_MemoryHierarchy 'Previously studied topic: Memory Hierarchy'
 BG_Studied_Assembly 'Previously studied topic: Assembly'
 BG_Studied_None 'Previously studied topic: None of the above'
 USE01 'The VR system was easy to learn'
 USE02 'I could navigate the environment without difficulty'
 USE03 'The controls felt intuitive'
 USE04 'The visual presentation made the concepts easier to follow'
 USE05 'I could focus on the learning task without being distracted by the interface'
 USE06 'I would feel confident using this system again'
 USE07_Discomfort 'I experienced discomfort, motion sickness, or visual fatigue while using the system'
 USE07_Comfort_R 'Reverse-coded comfort item'
 UsabilityMean_6 'Mean of usability items USE01-USE06'
 UsabilityMean_7R 'Mean of usability items USE01-USE06 plus reverse-coded comfort'
 ENG01 'The experience held my attention'
 ENG02 'I felt actively involved in the learning process'
 ENG03 'The system made the topic feel more interesting'
 ENG04 'I was motivated to explore the concepts further'
 ENG05 'The interactive format improved my focus compared with standard learning materials'
 EngagementMean 'Mean of engagement items ENG01-ENG05'
 LEARN01 'The VR experience helped me understand the topic better'
 LEARN02 'The visualisations helped me build a mental model of what was happening'
 LEARN03 'The system made abstract processes easier to understand'
 LEARN04 'I would prefer this as a supplement to traditional teaching materials'
 LEARN05 'I believe I learned something useful from this session'
 LearningExperienceMean 'Mean of learning-experience items LEARN01-LEARN05'
 PRE_Q11_RESP 'Baseline response Q11'
 PRE_Q11_CORR 'Baseline correctness Q11'
 PRE_Q12_RESP 'Baseline response Q12'
 PRE_Q12_CORR 'Baseline correctness Q12'
 PRE_Q13_RESP 'Baseline response Q13'
 PRE_Q13_CORR 'Baseline correctness Q13'
 PRE_Q14_RESP 'Baseline response Q14'
 PRE_Q14_CORR 'Baseline correctness Q14'
 PRE_Q25_RESP 'Baseline response Q25'
 PRE_Q25_CORR 'Baseline correctness Q25'
 POST_Q11_RESP 'Post-session response Q11: Which register stores the address of the next instruction?'
 POST_Q11_CORR 'Post-session correctness Q11'
 POST_Q12_RESP 'Post-session response Q12: Which stage of the instruction cycle reads an instruction from memory?'
 POST_Q12_CORR 'Post-session correctness Q12'
 POST_Q13_RESP 'Post-session response Q13: During instruction execution, the instruction register primarily stores:'
 POST_Q13_CORR 'Post-session correctness Q13'
 POST_Q14_RESP 'Post-session response Q14: What happens to the program counter after an instruction is fetched?'
 POST_Q14_CORR 'Post-session correctness Q14'
 POST_Q15_RESP 'Post-session response Q15: Which pipeline stage usually performs arithmetic operations?'
 POST_Q15_CORR 'Post-session correctness Q15'
 POST_Q16_RESP 'Post-session response Q16: Branch instructions primarily affect which component?'
 POST_Q16_CORR 'Post-session correctness Q16'
 POST_Q17_RESP 'Post-session response Q17: What does this instruction do? add $t0, $t1, $t2'
 POST_Q17_CORR 'Post-session correctness Q17'
 POST_Q18_RESP 'Post-session response Q18: What does this instruction do? addi $t0, $zero, 10'
 POST_Q18_CORR 'Post-session correctness Q18'
 POST_Q19_RESP 'Post-session response Q19: Which instruction type loads data from memory into a register?'
 POST_Q19_CORR 'Post-session correctness Q19'
 POST_Q20_RESP 'Post-session response Q20: What is the role of register $zero in MIPS?'
 POST_Q20_CORR 'Post-session correctness Q20'
 POST_Q21_RESP 'Post-session response Q21: What does this instruction do? lw $t0, 0($s0)'
 POST_Q21_CORR 'Post-session correctness Q21'
 POST_Q22_RESP 'Post-session response Q22: What does this instruction do? sw $t0, 4($s0)'
 POST_Q22_CORR 'Post-session correctness Q22'
 POST_Q23_RESP 'Post-session response Q23: What does this instruction do? beq $t0, $t1, label'
 POST_Q23_CORR 'Post-session correctness Q23'
 POST_Q24_RESP 'Post-session response Q24: What does this instruction do? j label'
 POST_Q24_CORR 'Post-session correctness Q24'
 POST_Q25_RESP 'Post-session response Q25: Put the instruction stages in the correct order.'
 POST_Q25_CORR 'Post-session correctness Q25'
 PRE_Knowledge5_NValid 'Count of nonmissing baseline items Q11, Q12, Q13, Q14, Q25'
 PRE_Knowledge5_Total 'Baseline matched five-item knowledge total'
 POST_Knowledge5_Total 'Post-session total on five repeated knowledge items (Q11-Q14, Q25)'
 Knowledge5_Gain 'Matched five-item knowledge gain'
 KnowledgeMatched_Available_NValid 'Number of repeated matched items answered at baseline'
 PRE_KnowledgeMatched_Available_Total 'Baseline total across the participant-specific matched available-item subset'
 POST_KnowledgeMatched_Available_Total 'Post-session total across the participant-specific matched available-item subset'
 KnowledgeMatched_Available_Gain 'Gain across the participant-specific matched available-item subset'
 PRE_KnowledgeMatched_Available_Percent 'Baseline percent across the participant-specific matched available-item subset'
 POST_KnowledgeMatched_Available_Percent 'Post-session percent across the participant-specific matched available-item subset'
 KnowledgeMatched_Available_GainPercent 'Percent gain across the participant-specific matched available-item subset'
 POST_Knowledge15_Total 'Full post-session knowledge total'
 POST_Knowledge15_Percent 'Full post-session knowledge percent'
 POST_KnowledgeConfidence 'Post-session confidence in knowledge-check answers'.

VALUE LABELS BG_Age18Plus BG_PriorArchitecture BG_PriorVR BG_Studied_InstructionFlow BG_Studied_Pipelining BG_Studied_Stack BG_Studied_MemoryHierarchy BG_Studied_Assembly BG_Studied_None
 0 'No / Not selected'
 1 'Yes / Selected'.

VALUE LABELS BG_VRExperience
 1 'None'
 2 'Limited'
 3 'Moderate'
 4 'Good'
 5 'High'.

VALUE LABELS BG_PriorConfidence
 1 'Extremely not confident'
 2 'Somewhat not confident'
 3 'Neutral'
 4 'Somewhat confident'
 5 'Extremely confident'.

VALUE LABELS BG_PriorDifficulty
 1 'Extremely difficult'
 2 'Somewhat difficult'
 3 'Neutral'
 4 'Somewhat easy'
 5 'Extremely easy'.

VALUE LABELS USE01 USE02 USE03 USE04 USE05 USE06 USE07_Discomfort ENG01 ENG02 ENG03 ENG04 ENG05 LEARN01 LEARN02 LEARN03 LEARN04 LEARN05
 1 'Strongly Disagree'
 2 'Disagree'
 3 'Neutral'
 4 'Agree'
 5 'Strongly Agree'.

VALUE LABELS USE07_Comfort_R
 1 'Very uncomfortable'
 2 'Uncomfortable'
 3 'Neutral'
 4 'Comfortable'
 5 'Very comfortable'.

VALUE LABELS POST_KnowledgeConfidence
 1 'Not at all confident'
 2 '2'
 3 '3'
 4 '4'
 5 'Very confident'.

VALUE LABELS PRE_Q11_RESP
 1 'Stack Pointer'
 2 'Program Counter'
 3 'Instruction Register'
 4 'Base Register'.

VALUE LABELS PRE_Q12_RESP
 1 'Decode'
 2 'Fetch'
 3 'Execute'
 4 'Write-back'.

VALUE LABELS PRE_Q13_RESP
 1 'Program variables'
 2 'The currently executing instruction'
 3 'The stack pointer value'
 4 'Cache addresses'.

VALUE LABELS PRE_Q14_RESP
 1 'It resets to zero'
 2 'It increments to the next instruction address'
 3 'It copies into the stack pointer'
 4 'It stores the result of the ALU'.

VALUE LABELS PRE_Q25_RESP
 1 'Execute, Fetch, Decode, Write-back'
 2 'Fetch, Decode, Execute, Write-back'
 3 'Decode, Fetch, Execute, Write-back'
 4 'Fetch, Execute, Decode, Write-back'.

VALUE LABELS POST_Q11_RESP
 1 'Stack Pointer'
 2 'Program Counter'
 3 'Instruction Register'
 4 'Base Register'.

VALUE LABELS POST_Q12_RESP
 1 'Decode'
 2 'Fetch'
 3 'Execute'
 4 'Write-back'.

VALUE LABELS POST_Q13_RESP
 1 'Program variables'
 2 'The currently executing instruction'
 3 'The stack pointer value'
 4 'Cache addresses'.

VALUE LABELS POST_Q14_RESP
 1 'It resets to zero'
 2 'It increments to the next instruction address'
 3 'It copies into the stack pointer'
 4 'It stores the result of the ALU'.

VALUE LABELS POST_Q15_RESP
 1 'Fetch'
 2 'Decode'
 3 'Execute'
 4 'Write-back'.

VALUE LABELS POST_Q16_RESP
 1 'Cache memory'
 2 'Program counter'
 3 'Stack pointer'
 4 'Instruction register'.

VALUE LABELS POST_Q17_RESP
 1 'Adds $t1 and $t2 and stores the result in $t0'
 2 'Adds $t0 and $t1 and stores the result in $t2'
 3 'Moves $t1 into $t2'
 4 'Multiplies registers'.

VALUE LABELS POST_Q18_RESP
 1 'Stores 10 into $t0'
 2 'Clears $t0'
 3 'Moves $t0 into $zero'
 4 'Adds two registers'.

VALUE LABELS POST_Q19_RESP
 1 'ADD'
 2 'STORE'
 3 'LOAD'
 4 'JUMP'.

VALUE LABELS POST_Q20_RESP
 1 'Stores the program counter'
 2 'Always contains the value 0'
 3 'Stores return addresses'
 4 'Tracks the stack pointer'.

VALUE LABELS POST_Q21_RESP
 1 'Stores $t0 into memory'
 2 'Loads a word from memory into $t0'
 3 'Moves $s0 into $t0'
 4 'Clears memory'.

VALUE LABELS POST_Q22_RESP
 1 'Value from $t0 is stored in memory'
 2 'Value from memory is loaded into $t0'
 3 '$s0 is overwritten'
 4 'Stack pointer moves'.

VALUE LABELS POST_Q23_RESP
 1 'Jump if $t0 > $t1'
 2 'Jump if $t0 == $t1'
 3 'Jump if $t0 < $t1'
 4 'Always jump'.

VALUE LABELS POST_Q24_RESP
 1 'Jumps to label unconditionally'
 2 'Jumps only if two registers are equal'
 3 'Stores the return address in $ra'
 4 'Loads a value from memory'.

VALUE LABELS POST_Q25_RESP
 1 'Execute, Fetch, Decode, Write-back'
 2 'Fetch, Decode, Execute, Write-back'
 3 'Decode, Fetch, Execute, Write-back'
 4 'Fetch, Execute, Decode, Write-back'.

VALUE LABELS PRE_Q11_CORR PRE_Q12_CORR PRE_Q13_CORR PRE_Q14_CORR PRE_Q25_CORR POST_Q11_CORR POST_Q12_CORR POST_Q13_CORR POST_Q14_CORR POST_Q15_CORR POST_Q16_CORR POST_Q17_CORR POST_Q18_CORR POST_Q19_CORR POST_Q20_CORR POST_Q21_CORR POST_Q22_CORR POST_Q23_CORR POST_Q24_CORR POST_Q25_CORR
 0 'Incorrect'
 1 'Correct'.

VARIABLE LEVEL
 ParticipantID (NOMINAL)
 BG_Age18Plus (NOMINAL)
 BG_PriorArchitecture (NOMINAL)
 BG_PriorVR (NOMINAL)
 BG_Studied_InstructionFlow (NOMINAL)
 BG_Studied_Pipelining (NOMINAL)
 BG_Studied_Stack (NOMINAL)
 BG_Studied_MemoryHierarchy (NOMINAL)
 BG_Studied_Assembly (NOMINAL)
 BG_Studied_None (NOMINAL)
 PRE_Q11_RESP (NOMINAL)
 PRE_Q12_RESP (NOMINAL)
 PRE_Q13_RESP (NOMINAL)
 PRE_Q14_RESP (NOMINAL)
 PRE_Q25_RESP (NOMINAL)
 PRE_Q11_CORR (NOMINAL)
 PRE_Q12_CORR (NOMINAL)
 PRE_Q13_CORR (NOMINAL)
 PRE_Q14_CORR (NOMINAL)
 PRE_Q25_CORR (NOMINAL)
 POST_Q11_RESP (NOMINAL)
 POST_Q12_RESP (NOMINAL)
 POST_Q13_RESP (NOMINAL)
 POST_Q14_RESP (NOMINAL)
 POST_Q15_RESP (NOMINAL)
 POST_Q16_RESP (NOMINAL)
 POST_Q17_RESP (NOMINAL)
 POST_Q18_RESP (NOMINAL)
 POST_Q19_RESP (NOMINAL)
 POST_Q20_RESP (NOMINAL)
 POST_Q21_RESP (NOMINAL)
 POST_Q22_RESP (NOMINAL)
 POST_Q23_RESP (NOMINAL)
 POST_Q24_RESP (NOMINAL)
 POST_Q25_RESP (NOMINAL)
 POST_Q11_CORR (NOMINAL)
 POST_Q12_CORR (NOMINAL)
 POST_Q13_CORR (NOMINAL)
 POST_Q14_CORR (NOMINAL)
 POST_Q15_CORR (NOMINAL)
 POST_Q16_CORR (NOMINAL)
 POST_Q17_CORR (NOMINAL)
 POST_Q18_CORR (NOMINAL)
 POST_Q19_CORR (NOMINAL)
 POST_Q20_CORR (NOMINAL)
 POST_Q21_CORR (NOMINAL)
 POST_Q22_CORR (NOMINAL)
 POST_Q23_CORR (NOMINAL)
 POST_Q24_CORR (NOMINAL)
 POST_Q25_CORR (NOMINAL)
 BG_VRExperience (ORDINAL)
 BG_PriorConfidence (ORDINAL)
 BG_PriorDifficulty (ORDINAL)
 POST_KnowledgeConfidence (ORDINAL)
 USE01 (ORDINAL)
 USE02 (ORDINAL)
 USE03 (ORDINAL)
 USE04 (ORDINAL)
 USE05 (ORDINAL)
 USE06 (ORDINAL)
 USE07_Discomfort (ORDINAL)
 USE07_Comfort_R (ORDINAL)
 ENG01 (ORDINAL)
 ENG02 (ORDINAL)
 ENG03 (ORDINAL)
 ENG04 (ORDINAL)
 ENG05 (ORDINAL)
 LEARN01 (ORDINAL)
 LEARN02 (ORDINAL)
 LEARN03 (ORDINAL)
 LEARN04 (ORDINAL)
 LEARN05 (ORDINAL)
 UsabilityMean_6 (SCALE)
 UsabilityMean_7R (SCALE)
 EngagementMean (SCALE)
 LearningExperienceMean (SCALE)
 PRE_Knowledge5_NValid (SCALE)
 PRE_Knowledge5_Total (SCALE)
 POST_Knowledge5_Total (SCALE)
 Knowledge5_Gain (SCALE)
 KnowledgeMatched_Available_NValid (SCALE)
 PRE_KnowledgeMatched_Available_Total (SCALE)
 POST_KnowledgeMatched_Available_Total (SCALE)
 KnowledgeMatched_Available_Gain (SCALE)
 PRE_KnowledgeMatched_Available_Percent (SCALE)
 POST_KnowledgeMatched_Available_Percent (SCALE)
 KnowledgeMatched_Available_GainPercent (SCALE)
 POST_Knowledge15_Total (SCALE)
 POST_Knowledge15_Percent (SCALE).

FORMATS ParticipantID BG_Age18Plus BG_PriorArchitecture BG_PriorVR BG_VRExperience BG_PriorConfidence BG_PriorDifficulty BG_Studied_InstructionFlow BG_Studied_Pipelining BG_Studied_Stack BG_Studied_MemoryHierarchy BG_Studied_Assembly BG_Studied_None USE01 USE02 USE03 USE04 USE05 USE06 USE07_Discomfort USE07_Comfort_R ENG01 ENG02 ENG03 ENG04 ENG05 LEARN01 LEARN02 LEARN03 LEARN04 LEARN05 PRE_Q11_RESP PRE_Q12_RESP PRE_Q13_RESP PRE_Q14_RESP PRE_Q25_RESP PRE_Q11_CORR PRE_Q12_CORR PRE_Q13_CORR PRE_Q14_CORR PRE_Q25_CORR POST_Q11_RESP POST_Q12_RESP POST_Q13_RESP POST_Q14_RESP POST_Q15_RESP POST_Q16_RESP POST_Q17_RESP POST_Q18_RESP POST_Q19_RESP POST_Q20_RESP POST_Q21_RESP POST_Q22_RESP POST_Q23_RESP POST_Q24_RESP POST_Q25_RESP POST_Q11_CORR POST_Q12_CORR POST_Q13_CORR POST_Q14_CORR POST_Q15_CORR POST_Q16_CORR POST_Q17_CORR POST_Q18_CORR POST_Q19_CORR POST_Q20_CORR POST_Q21_CORR POST_Q22_CORR POST_Q23_CORR POST_Q24_CORR POST_Q25_CORR PRE_Knowledge5_NValid PRE_Knowledge5_Total POST_Knowledge5_Total Knowledge5_Gain KnowledgeMatched_Available_NValid PRE_KnowledgeMatched_Available_Total POST_KnowledgeMatched_Available_Total KnowledgeMatched_Available_Gain POST_Knowledge15_Total POST_KnowledgeConfidence (F8.0).
FORMATS UsabilityMean_6 UsabilityMean_7R EngagementMean LearningExperienceMean PRE_KnowledgeMatched_Available_Percent POST_KnowledgeMatched_Available_Percent KnowledgeMatched_Available_GainPercent POST_Knowledge15_Percent (F8.2).
EXECUTE.
